// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBHuJ5sJNcT1BVXLq6uH4r14tzQ5shs-A',
    appId: '1:590558253329:web:fad88c4f0a558783887cb0',
    messagingSenderId: '590558253329',
    projectId: 'puranika-sadana',
    authDomain: 'puranika-sadana.firebaseapp.com',
    storageBucket: 'puranika-sadana.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYAqTSkdg3L2cw6RMtmzjrOk_bQnz3Y2k',
    appId: '1:590558253329:android:9b3c02916f6b9f11887cb0',
    messagingSenderId: '590558253329',
    projectId: 'puranika-sadana',
    storageBucket: 'puranika-sadana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcCY0-tjQs8b-vDqHrLvHa4ExKzUdubKw',
    appId: '1:590558253329:ios:2035aedb1c5acb74887cb0',
    messagingSenderId: '590558253329',
    projectId: 'puranika-sadana',
    storageBucket: 'puranika-sadana.firebasestorage.app',
    iosBundleId: 'com.puranika.sadana.puranikaSadana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcCY0-tjQs8b-vDqHrLvHa4ExKzUdubKw',
    appId: '1:590558253329:ios:2035aedb1c5acb74887cb0',
    messagingSenderId: '590558253329',
    projectId: 'puranika-sadana',
    storageBucket: 'puranika-sadana.firebasestorage.app',
    iosBundleId: 'com.puranika.sadana.puranikaSadana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBHuJ5sJNcT1BVXLq6uH4r14tzQ5shs-A',
    appId: '1:590558253329:web:43d94fa1907b33e7887cb0',
    messagingSenderId: '590558253329',
    projectId: 'puranika-sadana',
    authDomain: 'puranika-sadana.firebaseapp.com',
    storageBucket: 'puranika-sadana.firebasestorage.app',
  );
}
